name: Lint and Test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    name: "Lint and Test"
    steps:
      - name: Checkout Code
        id: checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        id: install
        run: npm i

      - name: Run Linter
        id: lint
        run: npm run lint

      - name: Run Tests
        id: test
        run: npm run test
        env:
          COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}

      - name: Build
        id: build
        run: npm run build

      - name: Check that ./dist is up to date
        run: git add dist && git diff --cached --exit-code --quiet
